"""Generate the local Bootstrap Icons subset.

Install the pinned Python dependency with:
python -m pip install -r tools/requirements-icons.txt
"""

from __future__ import annotations

import re
from pathlib import Path

from fontTools import subset


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
WEB_APP_ROOT = REPOSITORY_ROOT / "MiniPainterHub.WebApp"
BOOTSTRAP_ICONS_ROOT = REPOSITORY_ROOT / "e2e" / "node_modules" / "bootstrap-icons" / "font"
SOURCE_CSS = BOOTSTRAP_ICONS_ROOT / "bootstrap-icons.css"
SOURCE_FONT = BOOTSTRAP_ICONS_ROOT / "fonts" / "bootstrap-icons.woff"
OUTPUT_CSS = WEB_APP_ROOT / "wwwroot" / "css" / "bootstrap-icons-subset.css"
OUTPUT_FONT = WEB_APP_ROOT / "wwwroot" / "fonts" / "bootstrap-icons-subset.woff"

ICON_USAGE_PATTERN = re.compile(r"\bbi-([a-z0-9][a-z0-9-]*)\b", re.IGNORECASE)
ICON_RULE_PATTERN = re.compile(
    r'\.bi-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([a-f0-9]+)";\s*\}',
    re.IGNORECASE,
)


def collect_used_icons() -> list[str]:
    icons: set[str] = set()
    for razor_file in WEB_APP_ROOT.rglob("*.razor"):
        source = razor_file.read_text(encoding="utf-8")
        icons.update(match.group(1).lower() for match in ICON_USAGE_PATTERN.finditer(source))
    return sorted(icons)


def load_icon_codepoints() -> dict[str, int]:
    source = SOURCE_CSS.read_text(encoding="utf-8")
    return {
        match.group(1).lower(): int(match.group(2), 16)
        for match in ICON_RULE_PATTERN.finditer(source)
    }


def write_subset_font(codepoints: list[int]) -> None:
    options = subset.Options()
    options.flavor = "woff"
    font = subset.load_font(str(SOURCE_FONT), options)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    subset.save_font(font, str(OUTPUT_FONT), options)


def write_subset_css(icons: list[str], mappings: dict[str, int]) -> None:
    lines = [
        "/* Generated by tools/generate_bootstrap_icons_subset.py. */",
        "@font-face {",
        '    font-family: "bootstrap-icons";',
        '    src: url("../fonts/bootstrap-icons-subset.woff") format("woff");',
        "    font-display: block;",
        "}",
        "",
        ".bi::before,",
        '[class^="bi-"]::before,',
        '[class*=" bi-"]::before {',
        "    display: inline-block;",
        '    font-family: "bootstrap-icons" !important;',
        "    font-style: normal;",
        "    font-weight: normal !important;",
        "    font-variant: normal;",
        "    text-transform: none;",
        "    line-height: 1;",
        "    vertical-align: -0.125em;",
        "    -webkit-font-smoothing: antialiased;",
        "    -moz-osx-font-smoothing: grayscale;",
        "}",
        "",
    ]

    lines.extend(
        f'.bi-{icon}::before {{ content: "\\{mappings[icon]:x}"; }}'
        for icon in icons
    )
    OUTPUT_CSS.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    if not SOURCE_CSS.exists() or not SOURCE_FONT.exists():
        raise SystemExit("Run `npm install --prefix e2e` before generating the icon subset.")

    icons = collect_used_icons()
    mappings = load_icon_codepoints()
    missing = sorted(set(icons) - mappings.keys())
    if missing:
        raise SystemExit(f"Bootstrap Icons has no mapping for: {', '.join(missing)}")

    write_subset_font([mappings[icon] for icon in icons])
    write_subset_css(icons, mappings)
    print(f"Generated {len(icons)} Bootstrap icon glyphs.")


if __name__ == "__main__":
    main()
